export const CREATE_OCCASION = "CREATE_OCCASION";
export const GET_USER_COLLECTIONS = "GET_USER_COLLECTIONS";
export const SET_CURRENT_OCCASION = "SET_CURRENT_OCCASION";
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const SET_CURRENT_CART = "SET_CURRENT_CART";
export const TOGGLE_PROFILE_MODAL = "TOGGLE_PROFILE_MODAL";
export const TOGGLE_LOGGED_STATUS = "TOGGLE_LOGGED_STATUS";
